routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('layouts.home');
});

//flow recommender
Route::get('/games/{game}/arrange/{community1}/vs/{community2}', 'GameController@arrange');
//Route::get('/games/queue','GameController@queue');

//find game, exclude creator
Route::get('/games/find','GameController@find');

//join function for game
Route::get('/games/join/{game}', 'GameController@join'); //ni ?? tul ??

//finish game
Route::get('/games/finish', 'GameController@finish');

//join function for community
Route::get('/communities/join/{community}', 'CommunityController@join'); 

//jadi tapi dia ambik index.blade
//skang ni nak panggil method index kt find
//tapi problemnye satu jer, satu route satu method jer ke ?

// Route::get('/games/find', function () {
//     return view('games.find');
// });
//join route ?????

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('profile', 'UserController@profile');

Route::get('users/{pemain}', 'UserController@show');

//create Multi game for tournament
Route::get('/games/createMulti' , 'GameController@createMulti');

//resource game
Route::resource('games', 'GameController');

//resource community, tak perfect tak fk kan so relationship cam sampah
Route::resource('communities', 'CommunityController');

//recomender controller and page
Route::get('/test','GameController@test');

//resource attribute
Route::resource('attributes','AttributeController');

//resource courts
Route::resource('courts','CourtController');

//resource voyager
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});



// Route::get('/games/create', 'GameController@create');
// Route::post('/games', 'GameController@store');
// Route::get('/games', 'GameController@index');
// Route::post('/games', 'GameController@edit');
// Route::get('/games', 'GameController@destroy');

// Route for show picture
// Route::get('profile', 'AvatarController@index') ->name('home');

app/Court.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Court extends Model
{
    //
    protected $guarded= [];

    public function games()
    {
        return $this->hasOne('App\Game');
    }
}

app/Http/Controllers/CourtController.php
<?php

namespace App\Http\Controllers;

use App\Court;
use Illuminate\Http\Request;

class CourtController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        // Court::create(Input::all());
        $courts = Court::all();
        return view('courts.index',compact('courts'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('courts.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // dd($request->all());
        
        $court = Court::create($request->all());
        return redirect()->route('courts.index');
        // return redirect()->route('admin.courts.index'); //ni ada salah
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Court  $court
     * @return \Illuminate\Http\Response
     */
    public function show(Court $court)
    {
        return view('courts.show',compact('court'));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Court  $court
     * @return \Illuminate\Http\Response
     */
    public function edit(Court $court)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Court  $court
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Court $court)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Court  $court
     * @return \Illuminate\Http\Response
     */
    public function destroy(Court $court)
    {
        //
    }
}

resources/views/courts/create.blade.php
@extends('layouts.app')
  
@section('content')


<!--New Map-->
<div class="container">
    <div class="col-sm-12">
        <h1>Add Court Location</h1>
        <div class="form-group">
        <form method="POST" action="{{route('courts.store')}}">
            @csrf
            <div class="form-group">
                <label for="">Title</label>
                <input type="text" class="form-control input-sm" name="name">
            </div>
            <div class="form-group">
                <label for="address_address">Address</label>
                <input type="text" id="address-input" name="address_address" class="form-control map-input">
                <input type="hidden" id="address-latitude" name="address_latitude" value="0" />
                <input type="hidden" id="address-longitude" name="address_longitude" value="0" />
            </div>
            <div id="address-map-container" style="width:100%;height:400px; ">
                <div style="width: 100%; height: 100%" id="address-map"></div>
            </div>

            <button class="btn btn-sm btn-danger" type="submit">Save</button>
        </form>
        </div>
    </div>
</div>


@section('scripts')
    @parent
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCPvCAl7pbuPZ_oUm_dodxXi6oJDho_fdM&libraries=places&callback=initialize" async defer ></script>
{{-- <script src="/js/courtsMap.js"></script> --}}
<script src="/js/mapInput.js"></script>

@stop

@yield('scripts')

@endsection

resources/views/courts/index.blade.php
@extends('layouts.app')
 
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Court ID</td>
          <td>Court Name</td>
          <td>Address</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($courts as $court)
        <tr>
            <td>{{$court->id}}</td>
            <td>{{$court->name}}</td>
            <td>{{$court->address_address}}</td>
        <td> <a href="{{route('courts.show',$court)}}" ><div class="btn btn-primary">View</div></a>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection

resources/views/courts/show.blade.php
@extends('layouts.app')
  
@section('content')

<!--New Map-->
<div class="container">
    <div class="col-sm-12">
        <h1></h1>
        <div class="form-group">
            <h1 >{{$court->name}}</h1>
            <h1 >{{$court->address_address}}</h1>

            <div id="address-map-container" style="width:100%;height:400px; ">
                <div style="width: 100%; height: 100%" id="address-map"></div>
            </div>

        </div>
    </div>
</div>


@section('javascript')
    @parent
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCPvCAl7pbuPZ_oUm_dodxXi6oJDho_fdM&libraries=places&callback=initialize"></script>
<script type="text/javascript">
function initialize() {
    var myLatLng = {lat: {{$court->address_latitude}}, lng: {{$court->address_longitude}}};
        // Load the map and puts the center marker
        var map = new google.maps.Map(document.getElementById('address-map'), {
            center: myLatLng,
            zoom: 13,
        });
        marker = new google.maps.Marker({
            map: map,
            position: myLatLng,
            draggable: true,
        });
  }
  </script>

@stop

@endsection