routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('layouts.home');
});

//flow recommender
Route::get('/games/{game}/arrange/{community1}/vs/{community2}', 'GameController@arrange');
//Route::get('/games/queue','GameController@queue');

//find game, exclude creator
Route::get('/games/find','GameController@find');

//join function for game
Route::get('/games/join/{game}', 'GameController@join'); //ni ?? tul ??

//finish game
Route::get('/games/finish', 'GameController@finish');

//join function for community
Route::get('/communities/join/{community}', 'CommunityController@join'); 

//jadi tapi dia ambik index.blade
//skang ni nak panggil method index kt find
//tapi problemnye satu jer, satu route satu method jer ke ?

// Route::get('/games/find', function () {
//     return view('games.find');
// });
//join route ?????

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('profile', 'UserController@profile');

Route::get('users/{pemain}', 'UserController@show');

//create Multi game for tournament
Route::get('/games/createMulti' , 'GameController@createMulti');

//resource game
Route::resource('games', 'GameController');

//resource community, tak perfect tak fk kan so relationship cam sampah
Route::resource('communities', 'CommunityController');

//recomender controller and page
Route::get('/test','GameController@test');

//resource attribute
Route::resource('attributes','AttributeController');

//resource courts
Route::resource('courts','CourtController');

//resource voyager
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});



// Route::get('/games/create', 'GameController@create');
// Route::post('/games', 'GameController@store');
// Route::get('/games', 'GameController@index');
// Route::post('/games', 'GameController@edit');
// Route::get('/games', 'GameController@destroy');

// Route for show picture
// Route::get('profile', 'AvatarController@index') ->name('home');

app/Community.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Community extends Model
{
    //

    protected $fillable = [
        'community_name','description', 'user_id', 'total_users'];

   //one community , many user
    public function users()
    {
        return $this->belongsToMany('App\User');
    }

    //one community , many games
    public function games()
    {
        return $this->belongsToMany('App\Game');
    }
}

app/Http/Controllers/CommunityController.php
<?php

namespace App\Http\Controllers;

use App\Community;
use App\User;
use Illuminate\Http\Request;

class CommunityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $communities = Community::all();
        //select * from community

        return view('communities.index', compact('communities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //dd('create')

        return view ('communities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request)

        $request->validate([
            'community_name' => 'required'
        ]);

        $communities = Community::Create([
            'user_id'=> auth()->user()->id,
            'community_name' => $request['community_name'],
            'description' => $request['description'],
            'total_users'=> 1
        ]);

        $user = auth()->user();
        //dd($user);
        $user->communities()->attach($communities->id); //dia create dia auto join 
   
        return redirect("communities");


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\community  $community
     * @return \Illuminate\Http\Response
     */
    public function show(community $community)
    {
        //
        $users= $community->users;
        //id dkt parameter method so find($id) kirenya function tu akan kasi users yg dah join game based on id kau send
        //dd($game->users); //ambik users based on game id
        return view('communities.show', compact('communities', 'users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\community  $community
     * @return \Illuminate\Http\Response
     */
    public function edit(community $community)
    {
        //
        abort_if($community->user_id !=auth()->id(), 403);
        return view ('communities.edit', compact ('community'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\community  $community
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, community $community)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\community  $community
     * @return \Illuminate\Http\Response
     */
    public function destroy(community $community)
    {
        //
        $community->delete();

        return redirect()->route('communities.index') ->with('success', 'community deleted successfully');
    }

    public function join(community $community)
    {
        $user = auth()->user();// current user 
        $community->total_users = $community->total_users + 1; 
        $community->save();
        $user->communities()->attach($community->id);

        return redirect("communities");


        //join dah okay cuma, dia tak gi details  
    }


}

resources/views/communities/create.blade.php
@extends('layouts.app')

@section('content')

<head>
    <style>
    
    .page-header h1{
        padding-left: 10em; 
    }
    
    .img{
        height:300px;
        width:100%;
    }
    
    </style>
</head>

<div class="container">
    <div class="page-header">
        <h1>Create Community</h1>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="/communities" class="container" method="POST">
    {{csrf_field() }}

<!--Start table , row-->
<div class="row">
    <div class="col-md-7">
            <!--Community Name-->
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fa fa-info fa-fw"></i></span>
                <input type="text" name="community_name" value="{{ old('community_name') }}" class="form-control" placeholder="Community Name"
                style="text-transform: capitalize">
            </div>
            <br>

            <!--Description-->
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-asterisk"></i></span>
                    <textarea class="form-control" style="height:100px" name="description" placeholder="Detail such as state , districe, address"></textarea>
            </div>
            <br>

            <!--Submit and back button-->
            <div class="col-md-12 text-center clearfix" style="padding: 3em;">
                <button type="submit" class="btn btn-success">Submit</button>
                <a class="btn btn-danger" href="{{ route('communities.index') }}">Back</a>
                {{-- <a class="btn btn-primary" href=""> Back</a> --}}
            </div>

    </div>
</div>   
</form>

@endsection

resources/views/communities/delete.blade.php
@extends('layouts.app')

resources/views/communities/find.blade.php
@extends('layouts.app')

resources/views/communities/index.blade.php
@extends('layouts.app')
 
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }

  #createButton{
    line-height: 12px;
     width: 18px;
     font-size: 8pt;
     font-family: tahoma;
     margin-top: 1px;
     margin-right: 2px;
     position:absolute;
     top:0;
     right:0;
  }
  
</style>


<!--Card your community-->
<div class="px-4">
  <div class="card text-white bg-info mb-3" style="">
    <div class="card-header">
      Your Community 
      <div class="float-right">
      <a href="/communities/create" class="btn btn-outline-light ml-20" role="button" aria-pressed="true" id="createButton">Create Community</a>
      </div>
      
    </div>
    <div class="card-body">
      <h5 class="card-title">Create Your Own Community</h5>
      <p class="card-text">create a community to form a futsal team to play together.</p>
    </div>
    </div></div>

<br>

<!--Table for all community-->
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif

  <table class="table table-striped">
    <thead>
        <tr>
          <td>Community ID</td>
          <td>Community Name</td>
          <td>Description</td>
          <td>Total user</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($communities as $community)
        <tr>
            <td>{{$community->id}}</td>
            <td>{{$community->community_name}}</td>
            <td>{{$community->description}}</td>
            <td>{{$community->total_users}}</td>
            <!--condition check klau dah join takleh join-->
            @if(auth()->user()->id != $community->user_id)
            <td><a href="/communities/join/{{$community->id}}" class="btn btn-success">Join</a></td>
            @endif
            <!--condition check siapa dlm join-->
            @foreach($community->users as $user) 
            @if(auth()->user()->id == $user->id)
            <td><a href="{{ route('communities.show', $community->id)}}" class="btn btn-warning">View</a></td>
            @endif
            @endforeach
            <td>
                <!--condition ambik sama dgn join, creator jer boleh delete-->
                @if(auth()->user()->id == $community->user_id)
                <form action="{{ route('communities.destroy', $community->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
                @endif
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection

resources/views/communities/show.blade.php
<div class="row row-cols-1 row-cols-md-3">
    @foreach($users as $user)
        <div class="col-2 mb-4" >
          <div class="card">
            {{-- <img src="..." class="card-img-top" alt="..."> --}}
            <div class="card-body">
              <h5 class="card-title">{{$user->name}}</h5>
            </div>
          </div>
        </div>
    @endforeach
</div>