routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('layouts.home');
});

//flow recommender
Route::get('/games/{game}/arrange/{community1}/vs/{community2}', 'GameController@arrange');
//Route::get('/games/queue','GameController@queue');

//find game, exclude creator
Route::get('/games/find','GameController@find');

//join function for game
Route::get('/games/join/{game}', 'GameController@join'); //ni ?? tul ??

//finish game
Route::get('/games/finish', 'GameController@finish');

//join function for community
Route::get('/communities/join/{community}', 'CommunityController@join'); 

//jadi tapi dia ambik index.blade
//skang ni nak panggil method index kt find
//tapi problemnye satu jer, satu route satu method jer ke ?

// Route::get('/games/find', function () {
//     return view('games.find');
// });
//join route ?????

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('profile', 'UserController@profile');

Route::get('users/{pemain}', 'UserController@show');

//create Multi game for tournament
Route::get('/games/createMulti' , 'GameController@createMulti');

//resource game
Route::resource('games', 'GameController');

//resource community, tak perfect tak fk kan so relationship cam sampah
Route::resource('communities', 'CommunityController');

//recomender controller and page
Route::get('/test','GameController@test');

//resource attribute
Route::resource('attributes','AttributeController');

//resource courts
Route::resource('courts','CourtController');

//resource voyager
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});



// Route::get('/games/create', 'GameController@create');
// Route::post('/games', 'GameController@store');
// Route::get('/games', 'GameController@index');
// Route::post('/games', 'GameController@edit');
// Route::get('/games', 'GameController@destroy');

// Route for show picture
// Route::get('profile', 'AvatarController@index') ->name('home');

app/Game.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    //

        protected $guarded = [];

    //one game , have many user
    public function users()
    {
        return $this->belongsToMany('App\User');
    }

    //one game, one court
    public function court()
    {
        return $this->belongsTo('App\Court');
    }

    //one game, many community
    public function communities()
    {
        return $this->belongsToMany('App\Community');
    }
}

app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Community;
use App\Court;
use App\Game;
use App\Http\Traits\PositioningTraits;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class GameController extends Controller
{
    use PositioningTraits;
    //index method
    public function index()
    {
        $games = Game::all(); 
        //select * from projects where owner_id = 4
        
        //Forecast thingy
        $courts = Court::all();
        $forecast = [];
        return view('games.index', compact('games', 'forecast','courts'));
    }

    //Create method
    public function create(Game $game)
    {
        //dd('create');
        
        $communities = Community::all();
        $courts = Court::all();

        return view('games.create', compact('communities', 'courts'));
    }

    public function createMulti(Game $game)
    {
        //dd('create');

        return view('games.createMulti');
    }

    //Store method
    public function store(Request $request)
    {
        //dd($request['communityId1']);
        //dd($request->all());
        //coding untuk validate form kita, contoh nak date after or equal
        
        $request->validate([
            'match_title' => 'required|unique:games',
            'date_time' => 'required|after_or_equal:now',
            'amount' => 'required',
            'communityId1'=>'required',
            'communityId2'=>'required|different:communityId1'
        ]);
            

        $game = Game::create([
            
            'user_id' => auth()->user()->id, // only current user can create game
            'match_title' => $request['match_title'],
            'date_time' => $request['date_time'],
            'amount' => $request['amount'],
            'total_players'=> 1,
            'court_id' => $request['courtId'],
                    
        ]);

        $user = auth()->user();
        //dd($user);
        
       // $com1 = Community::find($request['communityId1']);//attach community pertama
        //dd($com1);

        //$players = $com1->users;
        
        $game->communities()->attach($request['communityId1']); 
        $game->communities()->attach($request['communityId2']); 
        $user->games()->attach($game->id);

        return redirect("games");
        
    }

    public function test(){

 
        $highestDefender = [];
        $highestRw =[];
        $highestLw =[];
        $highestStriker =[];

        // foreach($players as $player){
        //     //dd($player->rating>defender);
        //     $highestDefender[$player->name] = $player->rating->defender;
        //     $highestRw[$player->name] = $player->rating->right_wing;
        //     $highestLw[$player->name] = $player->rating->left_wing;
        //     $highestStriker[$player->name] = $player->rating->striker;
        // }

        arsort($highestDefender);
        arsort($highestRw);
        arsort($highestLw);
        arsort($highestStriker);

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Game  $game
     * @return \Illuminate\Http\Response
     */
    public function show(Game $game) 
    {
        
        // $games = Game::all();//aq panggil mcm ni , tapi tak proper sebab dia panggil semua user aq nk dia panggil user yg dh join jer
        $users= $game->users;
        //id dkt parameter method so find($id) kirenya function tu akan kasi users yg dah join game based on id kau send
        //dd($game->users); //ambik users based on game id
        //dd($game); 
        return view ('games.show', compact('game','users'));
    }


    public function edit(Game $game)
    {
        //
         abort_if($game->user_id != auth()->id(), 403); //dia nk check klau bukan user yg create takleh access
         return view ('games.edit',compact ('game')); 
    }


    public function update(Request $request, Game $game)
    {
  
    }


    public function destroy(Game $game)
    {
        
        $game->delete();

        abort_if($game->user_id != auth()->id(), 403); //dia nk check klau bukan user yg create takleh access
        return redirect()->route('games.index') ->with('success', 'Game delete successful');
    }

    public function find(){

        //$games = Game::all(); 

        $games = DB::table('games')->where('user_id', '!=', auth()->user()->id)->get();
        $courts = Court::all();
        
        // dd($games);

        //select * from projects where owner_id = 4

        return view('games.find', compact('games','courts'));
    }

    public function join(Game $game)
    {
        $user = auth()->user();

        //dd($game->community);
       
            //Dia nak check community tu community dalam game ke tak
            //dd($user->communities[0]["community_name"]);
            if($user->communities[0]["community_name"] != $game->communities[0]["community_name"] and
            $user->communities[0]["community_name"] != $game->communities[1]["community_name"]
            )//juve not equal acmilan or juve
            { 
                return back()->with('different', 'Awak bukan community yg boleh join');
            } 
      
        //@if($user->communities[0] != $game)
        
        //klau game tu dh penuh dia takleh join
        if($game->total_players >= 12)
        {
            return back()->with('penuh', 'this match is already full'); //return session full
        }

        $game->total_players = $game->total_players + 1;
        $game->save();
        $user->games()->attach($game->id);// attach biasa lepas game

        return redirect("games");

        //logic dia check game dia ambik, count cukup 10 ke tak klau lebih dia abort       
        // $user->games()->attach($game->id); //dia create dia auto join  
    }

    public function arrange(Game $game, Community $community1, Community $community2)
    {
        //dd($community2);
        //$games = DB::table('games')->where('user_id', '!=', auth()->user()->id)->get();
        // dd($game->users->first());

        $comm1checkplayerexist = false;
        $comm2checkplayerexist = false;

        foreach($game->users as $user) {
            foreach ($community1->users as $player1)
            {
                if($user->id == $player1->id)
                {
                    $comm1checkplayerexist = true;
                }
            }

            foreach ($community2->users as $player2)
            {
                if($user->id == $player2->id){
                    $comm2checkplayerexist = true;
                }
            }
        }

        if(!$comm1checkplayerexist || !$comm1checkplayerexist)
        {
            return redirect()->back()->withErrors('Must have at least one player in each community');
        }


        $highestDefender1 = [];
        $highestRw1 =[];
        $highestLw1 =[];
        $highestStriker1 =[];

        //dd($community1->users[1]->rating);
        foreach ($community1->users as $player)
        {
            foreach($game->users as $user) {

                if($user->id == $player->id){
                    //var_dump($player->rating);
                    $highestDefender1[] = $player->name." [".$player->rating->defender."]";
                    $highestRw1[] = $player->name." [".$player->rating->right_wing."]";
                    $highestLw1[] = $player->name." [".$player->rating->left_wing."]";
                    $highestStriker1[] = $player->name." [".$player->rating->striker."]";
                    }
            }
        }

        $namaTeam1=$community1->community_name;
        //dd($namaTeam1);

        $highestDefender2 = [];
        $highestRw2 =[];
        $highestLw2 =[];
        $highestStriker2 =[];

        foreach ($community2->users as $player)
        {
            ($player->rating);
            foreach($game->users as $user) {

                if($user->id == $player->id){           
            $highestDefender2[] = $player->name." [".$player->rating->defender."]";
            $highestRw2[] = $player->name." [".$player->rating->right_wing."]";
            $highestLw2[] = $player->name." [".$player->rating->left_wing."]";
            $highestStriker2[] = $player->name." [".$player->rating->striker."]";
                }
            }
        }

        $namaTeam2=$community2->community_name;
        //dd($namaTeam2);
        
        arsort($highestDefender1);//ini array
        arsort($highestRw1);
        arsort($highestLw1);
        arsort($highestStriker1);


        $team1Data = [];
        for($i=0; $i< count($highestDefender1); $i++)
        {
            $team1Data[$i] = array($highestDefender1[$i],$highestRw1[$i],$highestLw1[$i],$highestStriker1[$i]);
        }

        arsort($highestDefender2);//ini array
        arsort($highestRw2);
        arsort($highestLw2);
        arsort($highestStriker2);

        $team2Data = [];
        for($i=0; $i< count($highestDefender2); $i++)
        {
            $team2Data[$i]=array($highestDefender2[$i],$highestRw2[$i],$highestLw2[$i],$highestStriker2[$i]);
        }

        //dd($highestDefender);
        // return view('games.arrange', compact('highestDefender1','highestRw1','highestLw1', 'highestStriker1', 'highestDefender2', 'highestRw2', 'highestLw2', 'highestStriker2'));
        //dd($team1Data);
        return view('games.arrange', compact('team1Data','team2Data' ,'namaTeam1', 'namaTeam2')); 
        
    }

    public function finish(){
        return view('games.finish');
    }
}

//buat column bru pasal total player
//create field jadi 1 

resources/views/games/arrange.blade.php
@extends('layouts.app')
  
@section('content')
<!--stack overflow-->
{{-- @foreach($recomends as $recomend)
{{$recomend}}
@endforeach --}}

<div class="alert alert-info">
    Please insert your attributes if your rating = [0]
</div>

<div class="container">
<div class="row">
    
    <!--Team 1-->
    <div class="col-sm-6">
        <div class="card text-white bg-light mb-3">
            <div class="card-header" style="color:black;">{{$namaTeam1}}</div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                          <td style="color:#505050">Defender</td>
                          <td style="color:#505050">Right Wing</td>
                          <td style="color:#505050">Left Wing</td>
                          <td style="color:#505050">Striker</td>

                        </tr>
                    </thead>
                    <tbody>
                        
                        {{-- {{dd($highestDefender)}} --}}
                        @foreach ($team1Data as $position)
                            <tr>
                                <td style="color:#505050">{{$position[0]}}</td>
                                <td style="color:#505050">{{$position[1]}}</td>
                                <td style="color:#505050">{{$position[2]}}</td>
                                <td style="color:#505050">{{$position[3]}}</td>
                            </tr>
                        @endforeach
                    </tbody>
                  </table>
            </div>
          </div>
    </div>
    
    <!--Team 2-->
    <div class="col-sm-6">
        <div class="card text-white bg-dark mb-3">
            <div class="card-header">{{$namaTeam2}}</div>
            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                        <tr>
                          <td style="color:#FFFFFF">Defender</td>
                          <td style="color:#FFFFFF">Right Wing</td>
                          <td style="color:#FFFFFF">Left Wing</td>
                          <td style="color:#FFFFFF">Striker</td>

                        </tr>
                    </thead>
                    <tbody>
                        
                        @foreach ($team2Data as $position)
                            <tr>
                                <td style="color:#FFFFFF">{{$position[0]}}</td>
                                <td style="color:#FFFFFF">{{$position[1]}}</td>
                                <td style="color:#FFFFFF">{{$position[2]}}</td>
                                <td style="color:#FFFFFF">{{$position[3]}}</td>
                            </tr>
                        @endforeach
                    </tbody>
                  </table>
            </div>
          </div>
      </div>
</div>
</div>


<!--Hahahaha-->
<div class="col-md-12 text-center clearfix" style="padding: 3em;">
    <a class="btn btn-outline-primary" href="/games/finish">Next</a> <!--Button next page disabled klau tak cukup 12-->
    <a class="btn btn-outline-danger" onclick="window.history.back()">Back</a>

</div>
@endsection

resources/views/games/create.blade.php
@extends('layouts.app')
  
@section('content')

<head>
<style>

.page-header h1{
    padding-left: 10em; 
}

.img{
    height:300px;
    width:100%;
}

</style>
</head>

<!--Bootstrap date/time picker's files-->
<link rel="stylesheet" href="bootstrap-datetimepicker.min.css">
<script src="bootstrap-datetimepicker.min.js"></script>

<div class="container">
    <div class="page-header">
        <h1>New Game</h1>
    </div>
</div>
   
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
 
{{--One Match Form  --}}
<form action="/games" method="POST" class="container" id="oneMatch">
        {{ csrf_field() }}

<!--start table,row-->
<div class="row">
    <div class="col-md-12">
        
        <!--Input Community-->
        <div class="input-group-prepend">
        <span class="input-group-text"><i class="fa fa-sitemap fa-fw"></i></span> <!--fontawesome icon-->
        {{-- <input type="text" class="form-control" placeholder="Community"> --}}

        <!--1st Community selection-->
        <select id="communityId" name="communityId1" class="form-control" placeholder="Community">
            @foreach($communities as $community)
            <option value="{{$community->id}}">{{$community->community_name}}</option>
            @endforeach
        </select>
        &nbsp; &nbsp; <h3>Vs</h3> &nbsp; &nbsp;
        <!--1st Community selection--> 
        <select id="communityId" name="communityId2" class="form-control" placeholder="Community">
            @foreach($communities as $community)
            <option value="{{$community->id}}">{{$community->community_name}}</option>
            @endforeach
        </select>
        
        {{-- <option value="null">Select Community</option>
        <option value="89" >11 v 11 Townsville</option>
        <option value="141" >Merlimau 2</option>
        <option value="140" >Merlimau FC</option> --}}
        
        </div>              
        <br>  
            
        <!--Match Title-->
        <div class="input-group-prepend">
        <span class="input-group-text"><i class="fa fa-info fa-fw"></i></span>
        <input type="text" name="match_title" value="{{ old('match_title') }}" class="form-control" placeholder="Match Title"
        style="text-transform: capitalize" required>
        </div>
        <br>
        
        <!--Location-->
        <div class="input-group-prepend">
        <span class="input-group-text"><i class="fa fa-globe fa-fw"></i></span>
        <select id="courtId" name="courtId" class="form-control" placeholder="Court">
            @foreach($courts as $court)
            <option value="{{$court->id}}">{{$court->name}}</option>
            @endforeach
        </select>      
        </div>
        <br>            
            
        <!--Time Picker & date-->
        <div class="bfh-timepicker">
        <div class="input-group-prepend">
        <span class="input-group-text"><i class="fa fa-clock-o fa-fw"></i></span>
        <input type="datetime-local" name="date_time" value="{{ old('date_time') }}" class="form-control" placeholder="Date & Time" required>
        </div>
        </div>
        <br>
        
        <!--Amount-->
        <div class="input-group-prepend">
        <span class="input-group-text"><i class="fa fa-money fa-fw"></i></span>
        <input type="text" name="amount" value="{{ old('amount') }}" class="form-control" placeholder="amount"
        style="text-transform: capitalize" required>
        </div>
        </div>

    <!--Rivaldo-->
    {{-- <div class="col-md-7">
        <div><p>Click on the map to place a pin where the game will be!</p></div>
        <img src={{asset('img/map.png')}} style="height:300px;width:100%;">
        <div id="map"></div>
    </div> --}}
</div>
            
<div class="col-md-12 text-center clearfix" style="padding: 3em;">
    <button type="submit" class="btn btn-success">Create</button>
    <a class="btn btn-danger" onclick="window.history.back()">Back</a>
    {{-- <a class="btn btn-primary" href=""> Back</a> --}}
</div>

</form>

{{--         
    masuk lepas cost
    <input type="hidden" name="latitude" value="" id="latitude" />
        <input type="hidden" name="longitude" value="" id="longitude" />
        <input type="hidden" name="homeLocationLatitude" id="homeLocationLatitude" value="-33.867387" />
        <input type="hidden" name="homeLocationLongitude" id="homeLocationLongitude" value="-151.207629" />
    </div>
    <div class="col-md-7">
        <div><p>Click on the map to place a pin where the game will be!</p></div>
        <div id="map" style="height:300px;width:100%;"></div>
    </div>
</div> --}}

{{-- cancel button after creating --}}
@endsection

resources/views/games/createMulti.blade.php
@extends('layouts.app')

@section('content')
<head>
    <style>
    
    .page-header h1{
        padding-left: 10em; 
    }
    
    .img{
        height:300px;
        width:100%;
    }
    
    </style>
    </head>
    
    <!--Bootstrap date/time picker's files-->
    <link rel="stylesheet" href="bootstrap-datetimepicker.min.css">
    <script src="bootstrap-datetimepicker.min.js"></script>
    
    <div class="container">
        <div class="page-header">
            <h1>New Game</h1>
        </div>
    </div>
       
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
     
    {{--One Match Form  --}}
    <form action="/games" method="POST" class="container" id="oneMatch">
            {{ csrf_field() }}
    <div class="row">
        <div class="col-md-5">
            
            <!--Input Community-->
            <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-sitemap fa-fw"></i></span> <!--fontawesome icon-->
            {{-- <input type="text" class="form-control" placeholder="Community"> --}}
            <select id="communityId" name="community.id" class="form-control" placeholder="Community"></select>
            
            {{-- <option value="null">Select Community</option>
            <option value="89" >11 v 11 Townsville</option>
            <option value="141" >Merlimau 2</option>
            <option value="140" >Merlimau FC</option> --}}
            
            </div>              
            <br>  
                
            <!--Match Title-->
            <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-info fa-fw"></i></span>
            <input type="text" name="match_title" value="{{ old('match_title') }}" class="form-control" placeholder="Match Title"
            style="text-transform: capitalize" required>
            </div>
            <br>
            
            <!--Location-->
            <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-globe fa-fw"></i></span>
            <input type="text" name="location" value="{{ old('location') }}" class="form-control" placeholder="location"
            style="text-transform: capitalize" required>        
            </div>
            <br>            
                
            <!--Time Picker-->
            <div class="bfh-timepicker">
            <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-clock-o fa-fw"></i></span>
            <input type="datetime-local" name="date_time" value="{{ old('date_time') }}" class="form-control" placeholder="Date & Time" required>
            </div>
            </div>
            <br>
            
            <!--Amount-->
            <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-money fa-fw"></i></span>
            <input type="text" name="amount" value="{{ old('amount') }}" class="form-control" placeholder="amount"
            style="text-transform: capitalize" required>
            </div>
        </div>
    
        <!--Rivaldo-->
        <div class="col-md-7">
            <div><p>Click on the map to place a pin where the game will be!</p></div>
            <img src={{asset('img/rivaldo.jpg')}} style="height:300px;width:100%;">
            <div id="map"></div>
        </div>
    </div>
                
    <div class="col-md-12 text-center clearfix" style="padding: 3em;">
        <button type="submit" class="btn btn-success">Create</button>
        <a class="btn btn-danger" onclick="window.history.back()">Back</a>
        {{-- <a class="btn btn-primary" href=""> Back</a> --}}
    </div>
    
    </form>
    
    {{--         
        masuk lepas cost
        <input type="hidden" name="latitude" value="" id="latitude" />
            <input type="hidden" name="longitude" value="" id="longitude" />
            <input type="hidden" name="homeLocationLatitude" id="homeLocationLatitude" value="-33.867387" />
            <input type="hidden" name="homeLocationLongitude" id="homeLocationLongitude" value="-151.207629" />
        </div>
        <div class="col-md-7">
            <div><p>Click on the map to place a pin where the game will be!</p></div>
            <div id="map" style="height:300px;width:100%;"></div>
        </div>
    </div> --}}
    
    {{-- cancel button after creating --}}
@endsection

{{--             <div class="bfh-timepicker">
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Start Date:</strong>
                    <input type="datetime-local" name="date_time" value="{{ old('date_time') }}" placeholder="Detail">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>End Date:</strong>
                    <input type="datetime-local" name="end_date" value="{{ old('end_date') }}" placeholder="Detail">
                </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Amount</strong>
                    <input type="text" name="amount" class="form-control" value="{{ old('amount') }}" placeholder="amount">
                </div>
            </div> --}}

resources/views/games/edit.blade.php
@extends('layouts.app')
<!--Belum siap method edit dengan update, details tu belum settle, and tak tahu nak edit ape-->
@section('content')

<head>
<style>

</style>
</head>

<div class="container">
    <div class="page-header">
        <h1>Edit Details</h1>
    </div>
</div>
   
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
<form action="{{ route('games.update',$game->id) }}" class="container" method="POST">
    @csrf
    @method('PUT')

<!--Start table , row-->
<div class="row">
    <div class="col-md-7">
            <!--Match Name-->
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fa fa-info fa-fw"></i></span>
                <input type="text" name="match_title" value="{{ $game->match_title }}" class="form-control" placeholder="Match Title"
                style="text-transform: capitalize">
            </div>
            <br>

            <!--Amount-->
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fa fa-money fa-fw"></i></span>
                <input type="text" name="amount" value="{{ $game->amount }}" class="form-control" placeholder="amount"
                style="text-transform: capitalize">
            </div>
            <br>

            <!--Detail -->
            <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-asterisk"></i></span>
                    <textarea class="form-control" style="height:50px" name="detail" placeholder="Detail such as price per person , reason to change title, any direction to venue">{{ $game->detail }}</textarea>
            </div>
            <br>

            <!--Submit and back button-->
            <div class="col-md-12 text-center clearfix" style="padding: 3em;">
                <button type="submit" class="btn btn-success">Submit</button>
                <a class="btn btn-danger" href="{{ route('games.index') }}">Back</a>
                {{-- <a class="btn btn-primary" href=""> Back</a> --}}
            </div>

    </div>
</div>   
</form>
@endsection

resources/views/games/find.blade.php
@extends('layouts.app')
 
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Match ID</td>
          <td>Match Title</td>
          <td>Location</td>
          <td>Amount</td>
          <td>Date & Time</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($games as $game)
        <tr>
            <td>{{$game->id}}</td>
            <td>{{$game->match_title}}</td>
            @foreach($courts as $court)
            <td>{{$court->name}}</td>
            @endforeach
            <td>{{$game->amount}}</td>
            <td>{{$game->date_time}}</td>

        <td><a href="/games/join/{{$game->id}}" class="btn btn-success">Join</a></td>

            <td>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
  @if (session('different'))
  <div class="alert-danger" role="alert">
    {{ session('different') }}
    @endif
  @if (session('penuh'))
<div class="alert-danger" role="alert">
  {{ session('penuh') }}
</div>
  @endif
<div>
@endsection

resources/views/games/index.blade.php
@extends('layouts.app')
 
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>

<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  
  <table class="table table-striped">
    <thead>
        <tr>
          <td>Match ID</td>
          <td>Match Title</td>
          <td>Location</td>
          <td>Amount</td>
          <td>Date & Time</td>
          <td>Total players</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($games as $game)
        <tr>
            <td>{{$game->id}}</td>
            <td>{{$game->match_title}}</td>
            @foreach($courts as $court)
            <td>{{$court->name}}</td>
            @endforeach
            <td>{{$game->amount}}</td>
            <td>{{$game->date_time}}</td>
            <td>{{$game->total_players}}</td>

           <!--condition check siapa dlm join-->
           @foreach($game->users as $user) 
           @if(auth()->user()->id == $user->id)
           <td><a href="{{ route('games.show', $game->id)}}" class="btn btn-warning">View</a></td>
           @endif
           @endforeach
           
           <!--condition-->
           <td>
           @if(auth()->user()->id == $game->user_id)
           <form action="{{ route('games.destroy', $game->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            @endif
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection